---
title: "Primjena analize teksta u znanstvenim istraživanjima"
description: "..."
number-sections: true
title-block-banner: "#8B475D"
title-block-banner-color: "white"
---

## Uvod u temu i svrhu istraživanja

Doktorska disertacija Anastasije Menshikove pod naslovom "*Cultural change: Studying social interdependencies in public discourse with computational text analysis*" bavi se sociološkim proučavanjem kulturnih promjena kroz prizmu javnog diskursa, uz primjenu računalne analize teksta. Autorica polazi od teorijskih okvira analitičke sociologije i sociologije kulture promatrajući javni diskurs kao kolektivan fenomen oblikovan međudjelovanjem pojedinačnih (mikro-razina) dinamika i međusobnih odnosa različitih društvenih sfera. Ključno istraživačko pitanje jest kako i zašto dolazi do promjene kulture – shvaćene kao skup kolektivnih značenja i vrijednosti – kroz promjene u javnoj raspravi. U radu se ističe da se kultura reflektira u javnom diskursu te se njezine promjene mogu analizirati prateći promjene u obrascima javne komunikacije.

Svrha istraživanja je objasniti mehanizme kulturne promjene tako što se analiziraju javne rasprave o imigraciji u Švedskoj tijekom niza godina i događaja. Odabrani empirijski kontekst je švedski diskurs o imigraciji od 2008. do 2020. godine, razdoblje koje obuhvaća nekoliko važnih društvenih previranja uključujući seriju džihadističkih terorističkih napada u 2010-ima te tzv. "europsku izbjegličku krizu" 2015.–2016. godine. Ovi neočekivani događaji i političke krize poslužili su kao prirodni eksperimenti koji omogućuju istraživanje kako javni diskurs reagira na šokove. Disertacija nastoji objasniti pod kojim uvjetima i putem kojih procesa dolazi do zaokreta ili pomaka u načinu na koji javnost govori o imigraciji.

## Teorijski okvir i pristup

Teorijski, rad se oslanja na analitičku sociologiju i sociologiju kulture. Analitička sociologija naglasak stavlja na mehanizme koji povezuju individualne akcije s kolektivnim ishodima, a u ovom kontekstu to znači razumjeti kako pojedinačne promjene u izražavanju stavova ili sudjelovanju u diskursu mogu rezultirati širim promjenama kulturnih obrazaca u društvu. Sociologija kulture doprinosi razumijevanju kolektivnih značenja i narativa u društvu – primjerice, kako se koncept "imigracije" različito interpretira i kakva simbolička značenja nosi u različitim društvenim grupama ili sferama (npr. u medijima naspram na internetskim forumima). Kombinirajući ove perspektive, autorica javni diskurs promatra kao dinamičan sustav u kojem pojedinci svojim komunikacijskim djelovanjem stalno reproduciraju i mijenjaju kulturna značenja, pri čemu su istodobno pod utjecajem međusobno povezanih društvenih sfera (mediji, politička arena, online zajednice itd.).

Ovakav teorijski okvir implicira da se kulturne promjene trebaju proučavati multirazinski - i na razini pojedinaca (mikro-razina) i na razini agregatnih obrazaca (makro-razina). Na mikro-razini zanima nas kako pojedinci mijenjaju način na koji govore o nekoj temi (npr. mijenjaju li retoriku, ton ili fokus argumenata) te kako novi pojedinci ulaze ili izlaze iz rasprave. Na makro-razini, gledamo ukupne obrasce diskursa - koje teme postaju istaknutije ili sporednije, kako se mijenja opći ton i sadržaj javne rasprave kroz vrijeme ili pod utjecajem vanjskih događaja. Kulturalna promjena se ovdje očituje upravo u tim pomacima u kolektivnim obrascima govora i značenja.

Autorica postavlja hipotezu da se promjene u javnom diskursu događaju kroz dva osnovna mehanizma: (1) promjene kod istih pojedinaca – kada isti sudionici s vremenom promijene svoj način govora ili stavove te (2) promjene u sastavu sudionika – kada se mijenja tko sudjeluje u raspravi (npr. priključuju se novi glasovi ili neki odlaze), što naziva kompozicijskom promjenom sudionika. Ova distinkcija je važna jer isti agregatni ishod (npr. porast učestalosti neke teme u diskursu) može proizaći iz različitih procesa – bilo da ljudi promijene mišljenje/rječnik ili da novi ljudi s drukčijim mišljenjima uđu u raspravu. Teorijski doprinos stoga leži u razlučivanju tih mehanizama i razumijevanju njihove uloge u kulturnoj dinamici.

## Podaci i metoda računalne analize teksta

Kako bi ispitala navedene procese, Menshikova je prikupila opsežne skupove tekstualnih podataka iz više izvora javnog diskursa. Glavni empirijski fokus je na diskursu o imigraciji u Švedskoj, a korišteni su sljedeći podaci:

1. Online forum “Flashback” – najveći švedski internetski forum s milijunima poruka korisnika poslužio je kao izvor digitalnih tragova diskursa građana. Flashback ima stalan zapis korisničkih objava kroz vrijeme što omogućuje praćenje pojedinačnih korisnika i njihovog sudjelovanja u raspravama. Ukupno je analizirano oko 16 milijuna forumskih objava na teme vezane uz imigraciju u razdoblju duljem od desetljeća. Ovi podaci omogućili su praćenje diskursa "odozdo" među građanima i anonimnim sudionicima online rasprava.

2. Nacionalni dnevni listovi u Švedskoj prikupljeni su tekstovi članaka iz četiri najveća švedska dnevna lista od 2008. do 2020. godine. Ovaj medijski korpus predstavlja "mainstream" ili institucionalizirani javni diskurs. Korišten je za usporedbu s online forumom kako bi se vidjelo razlikuju li se (i kako se približavaju ili udaljavaju) diskurs u masovnim medijima naspram diskursa online zajednice kroz vrijeme.

3. Anketa o europskom javnom mnijenju (ESS) kako bi se ispitalo šire javno mnijenje o imigraciji uključeni su podaci Europskog društvenog istraživanja za više europskih zemalja. To su tradicionalni anketni podaci o stavovima građana prema imigrantima korišteni primarno u dijelu istraživanja gdje se mjeri stav prije i poslije terorističkih napada.

4. Korpus medijskih vijesti iz Europe koji je prikupljen iz višejezičnog korpusa medijskih članaka iz najvećih nacionalnih medija 19 europskih zemalja. Time se mjerila medijska pozornost posvećena temi imigracije u različitim zemljama i vremenskim trenucima, posebno uoči terorističkih napada, kako bi se ispitalo djeluje li medijski fokus kao katalizator promjene stavova.

5. Korišten je i skup podataka s Twittera (X-a) koji obuhvaća aktivnosti i praćenja korisnika iz Švedske tijekom 2010.–2020. godine. Ti podaci uključuju koga su koji korisnici pratili i koje sadržaje su objavljivali što pruža uvid u "svakodnevne interese" politički angažiranih građana online. Posebno je zabilježeno koje političare pojedini korisnici prate na Twitteru što je iskorišteno za inferiranje političkih sklonosti korisnika (npr. prati li netko više lijevo ili desno orijentirane političare).

Navedene raznolike podatke autorica analizira metodom računalne analize teksta – nizom kvantitativnih tehnika za obradu velikih korpusa tekstova. U središtu ove disertacije nalazi se tematsko modeliranje tekstova i to posebice polunadzirani pristup poznat kao "seeded topic modeling". Tematsko modeliranje obuhvaća statističke metode koje otkrivaju latentne teme u velikim skupovima dokumenata. Klasičan primjer je LDA model (*Latent Dirichlet Allocation*) koji potpuno nenadzirano pronalazi teme na temelju učestalosti su-pojavljivanja riječi. Međutim, standardni nenadzirani modeli ne garantiraju da će identificirane "teme" odgovarati istraživačkim konceptima od interesa. Stoga je Menshikova primijenila proširenu metodu – tematsko modeliranje s početnim ključnim riječima koja omogućuje kombinaciju induktivnog otkrivanja obrazaca u tekstu s deduktivnim usmjeravanjem modela prema unaprijed zadanim konceptima.

U praksi, “*seeded*” tematski model funkcionira tako da istraživač zada određene ključnoznačne riječi koje pripadaju određenim temama za koje je teorijski zainteresiran. Model zatim koristi te riječi kao “*sidra*” za teme: osigurava da će se oko tih pojmova formirati teme, ali istovremeno slobodno otkriva i druge relevantne riječi koje se pojavljuju u istom kontekstu. Time se postiže da teme budu smislenije i povezanije s teorijom, a ipak se dopušta modelu da prepozna nove obrasce i vokabular koji istraživač možda nije unaprijed predvidio. Ovakav polunadzirani pristup poboljšava interpretabilnost i replikabilnost rezultata jer su teme djelomično definirane što olakšava tumačenje, ali i dalje proizašle iz podataka što osigurava da reflektiraju stvarne obrasce u korpusu.

## Pregled istraživanja kroz četiri eseja disertacije

Rad je strukturiran kroz četiri povezana eseja (studije) od kojih se svaki bavi posebnim aspektom kulturne promjene u javnom diskursu koristeći računalnu analizu teksta kao glavni alat. U nastavku slijedi sažetak svakog eseja i objašnjenje kako je u njemu primijenjena analiza teksta.

**Prvi esej: Pojedinačni doprinosi promjeni diskursa nakon šokova**

Prvi esej istražuje kako iznenadni disruptivni događaji, konkretno niz džihadističkih terorističkih napada tijekom 2010-ih godina utječu na online diskurs o imigraciji u Švedskoj. Ključno pitanje glasi: mijenjaju li se opće teme i ton rasprave o imigraciji nakon takvih šokova zbog toga što isti ljudi počinju drugačije govoriti ili zato što se u raspravu uključuju novi ljudi? Kako bi odgovorila, autorica je koristila podatke foruma Flashback – koji bilježe kontinuiranu aktivnost korisnika – prije i poslije nekoliko terorističkih napada.

Pomoću računalne analize teksta identificirane su tri glavne interpretacije ili tematska okvira u diskusijama o imigraciji: kulturalni, sigurnosni i ekonomski. To praktično znači da su razgovori o imigraciji analizirani prema tome naglašavaju li pitanja kulture (identiteta, vrijednosti, religije), pitanja sigurnosti (kriminalitet, terorizam, javni red) ili ekonomska pitanja (tržište rada, socijalni sustav). Za svaku forumsku poruku utvrđeno je koliko je prisutan svaki od tih okvira (npr. metodom seeded topic modeling gdje su zadane ključne riječi vezane uz “*kulturu*”, “*sigurnost*” i “*ekonomiju*” kako bi model razlikovao te teme).

Analiza je pokazala da se nakon terorističkih napada značajno mijenja “istaknutost” pojedinih okvira u online diskursu. Konkretno, sigurnosni aspekt imigracije očekivano postaje mnogo zastupljeniji u raspravama neposredno nakon napada (porast spominjanja tema vezanih uz sigurnost i terorizam), dok se relativno smanjuje udio kulturnih i ekonomskih tema. Međutim, detaljna raščlamba je otkrila da taj agregatni pomak proizlazi iz dva paralelna procesa:

- Unutar-pojedinačna promjena: Mnogi korisnici koji su i prije sudjelovali u raspravama o imigraciji počeli su nakon napada više naglašavati teme sigurnosti (mijenjajući svoj diskurs). Dakle, isti pojedinci su prilagodili svoj govor novonastaloj situaciji, recimo povezujući imigraciju s pitanjima terorizma ili nacionalne sigurnosti znatno više nego ranije.

- Kompozicijska promjena sudionika: Istovremeno, u online raspravu su se uključili i novi korisnici (ili su se vratili ranije neaktivni) čija je prisutnost pomaknula ravnotežu tema. Ti novi glasovi često su imali specifičan interes za sigurnosni aspekt te su time doprinijeli da sigurnosni okvir postane dominantniji u ukupnoj raspravi.

Prvi esej, dakle, kvantitativno mjeri koliko svaki od ta dva mehanizma doprinosi uočenoj promjeni u diskursu. Zaključak je da oba mehanizma zajedno oblikuju promjenu – i promjene u načinu izražavanja postojećih sudionika i promjene u sastavu sudionika zajednički objašnjavaju zašto je nakon napada porasla važnost sigurnosnog okvira u diskursu. Ovim nalazom naglašava se važnost korištenja tekstualnih podataka na razini pojedinca: samo zahvaljujući tome što se pratilo što svaki korisnik piše kroz vrijeme, bilo je moguće razdvojiti efekat “promjene mišljenja” od efekta “nove publike”. Drugim riječima, računalna analiza teksta nad sadržajem pojedinačnih korisnika omogućila je uvid koji agregatne ankete ili opće statistike diskursa ne bi mogle dati. Ovaj esej teorijski doprinosi razumijevanju mikro-makro veze u kulturnim promjenama - pokazuje kako mikro-dinamika (promjene kod pojedinaca) može generirati makro-pomake u kolektivnoj kulturi već u kratkom roku, primjerice svega nekoliko tjedana nakon značajnog događaja.

**Drugi esej: Učinak terorističkih napada na stavove javnosti i uloga medija**

Drugi esej pomiče perspektivu s online diskursa u Švedskoj na širi europski kontekst i tradicionalno javno mnijenje. Pitanje koje se ovdje postavlja je dovode li teroristički napadi do promjene javnog mnijenja o imigraciji među građanima i igra li u tome ulogu koliko su mediji prije toga fokusirani na temu imigracije?. Ova studija koristi prirodni eksperimentalni pristup: uspoređuje stavove ispitanika prije i poslije 38 terorističkih napada koji su se dogodili u raznim europskim zemljama između 2013. i 2019. godine.

Za mjerenje stavova koristilo se Europsko društveno istraživanje (ESS) koje redovito prikuplja anketne podatke o socijalnim i političkim stavovima. Stavovi prema imigrantima iz tih anketa poslužili su kao mjera javnog mnijenja. Paralelno, za svaki od tih napada prikupljeni su medijski tekstovi iz najvećih nacionalnih medija zahvaćenih zemalja. Računalna analiza teksta korištena je kako bi se kvantificirala medijska pozornost na imigraciju prije napada, primjerice izračunavan je udio članaka o imigraciji u nacionalnim medijima u tjednima koji su prethodili svakom napadu. To je izvedeno pretraživanjem tekstova za ključne riječi vezane uz imigraciju ili uporabom tematskih modela prilagođenih za više jezika, kako bi se izolirala tema imigracije u korpusu vijesti.

Istraživanje je potom ispitalo mijenja li se stav ispitanika prema imigrantima nakon napada te razlikuje li se taj efekt ovisno o tome je li medijska pažnja na imigraciju bila visoka ili niska prije napada. Rezultati su bili pomalo iznenađujući: suprotno početnim očekivanjima, teroristički napadi nisu doveli do statistički značajnih promjena u stavovima prema imigraciji na razini šireg javnog mnijenja. Čak i kada su mediji intenzivno izvještavali o imigraciji prije napada (što se očekivalo da bi moglo “pogoršati” utjecaj napada na percepciju imigranata povezivanjem imigracije s terorizmom), nije uočen sustavan porast negativnog stava prema imigrantima. Drugim riječima, građani u prosjeku nisu postali značajno zatvoreniji ili negativnije nastrojeni prema imigraciji nakon tih incidenata, čak ni u uvjetima pojačane medijske prisutnosti teme imigracije.

Ovaj nalaz ukazuje na stabilnost javnog mnijenja naspram kratkoročnih šokova, ali i na to da medijski diskurs i javno mnijenje ne moraju biti usko povezani kako se ponekad pretpostavlja. Za metodologiju disertacije važan je i zaključak da je kombinacija raznovrsnih podataka i metoda dala najbogatiji uvid: klasični anketni podaci pružili su mjeru deklariranih stavova, dok je računalna analiza medijskih tekstova omogućila precizno mjerenje konteksta u kojem se ti stavovi formiraju (medijskog okruženja). Autorica ističe da integriranje “digitalnih tragova” teksta (poput sadržaja s društvenih mreža ili online medija) s tradicionalnim izvorima podataka (anketama, eksperimentima) značajno obogaćuje sociološka istraživanja. U ovom slučaju, tekstualna analiza novinskih članaka diljem Europe bio je ključan da bi se razumjelo ima li informacijski kontekst (npr. senzacionalističko izvještavanje o imigrantima) utjecaj na promjenu stavova – rezultati sugeriraju da, barem kod ovakvih ekstremnih događaja, efekt medija nije jednostavan niti linearan.

**Treći esej: Dugoročne promjene značenja u medijima i online forumu**

Treći esej usredotočen je na dugoročnu kulturnu promjenu i to kroz usporedbu dviju sfera javnog diskursa: mainstream medija (nacionalnih novina) i online foruma građana (Flashback). Glavno istraživačko pitanje glasi: jesu li se tijekom vremena kolektivna značenja i interpretacije imigracije u tradicionalnim medijima i na online forumu približile jedna drugoj ili su se udaljile? Posebno se analizira utjecaj “izbjegličke krize” 2015.–2016., događaja koji je dramatično obilježio diskusije o useljavanju diljem Europe, na konvergenciju ili divergenciju diskursa u te dvije sfere.

Ovdje se povezuju dvije prethodno opisane korpusne baze – zbirka članaka iz najvećih švedskih novina (2008.–2020.) i zbirka postova korisnika s Flashback foruma (također 2008.–2020.). Radi se o vrlo različitim tipovima tekstova (uređeni novinski članci naspram neformalnih online komentara) i vokabularu što otežava direktnu usporedbu. Autorica je stoga razvila metodološki pristup za usporedbu diskursa koji uzima u obzir te razlike: koristila je polunadzirano tematsko modeliranje (seeded topic modeling) prilagođeno tako da može istovremeno obraditi dvije razdvojene tekstualne zbirke. To praktično znači da je model treniran na kombiniranom korpusu novinskih i forumskih tekstova pri čemu su određene teme bile “usidrene” na ključne aspekte imigracije. Time se osiguralo da model prepoznaje iste tematske koncepte u oba korpusa unatoč tome što forumaši i novinari možda koriste posve drugačiji jezik za iste pojmove. Na primjer, tema vezana uz traženje azila mogla je biti definirana skupom seed-pojmova (poput “azil”, “izbjeglice”, “migrantska kriza”) tako da model prepozna tu temu bilo da se pojavljuje u novinama (koje možda koriste formalnije izraze) ili na forumu (gdje se mogu javiti žargonizmi ili kolokvijalni termini).

Nakon što je model identificirao usporedive teme/ okvire u oba korpusa, analizirana je sličnost kolektivnih značenja kroz vrijeme. Jedan od načina mjerenja bio je usporediti “mreže značenja” (engl. *meaning networks*) – mrežne odnose između pojmova u diskursu – u medijima i na forumu prije i poslije kriznog perioda. Posebna pozornost posvećena je tome približavaju li se te mreže tijekom izbjegličke krize (što bi značilo da mediji i forum počinju pričati o imigraciji na sličniji način) ili se pak razilaze (što bi značilo da se javlja veći rascjep između službenog diskursa i onoga “na terenu”).

Rezultati su pokazali zanimljiv trend: tijekom 2015.–2016., za vrijeme vrhunca priljeva izbjeglica, diskursi u mainstream medijima i na forumu su se međusobno približili. Drugim riječima, došlo je do konvergencije kulturnih značenja: teme i okviri o kojima su pisale novine i oni o kojima su raspravljali građani na forumu postali su sličniji nego prije. Konkretno, analize su pokazale da su se u oba prostora istaknuli slični problemi i narativi – npr. i novine i forumaši intenzivno su raspravljali o kapacitetu prihvata izbjeglica, integraciji, humanitarnoj odgovornosti ali i izazovima za sustav. Prije krize, te dvije sfere su imale veći raskorak: mainstream mediji držali su se uglavnom institucionalnih tema i uglavnom pozitivnog okvira (fokus na humanitarnom aspektu i integraciji), dok je na Flashbacku diskurs bio raznolikiji i često kritičniji (više naglasaka na kriminalitetu, kontroli granica itd.). No, izbjeglička kriza je bila takvog obima da je usidrila pažnju svih na određene ključne teme što je rezultiralo time da su i novinski i forumski diskurs morali obraditi slične probleme, možda svaki na svoj način, ali više usuglašeni u temama nego ranije.

Važno je istaknuti da je korištenje računalne analize teksta ovdje omogućilo kvantificiranu usporedbu dva vrlo različitih izvora. Tradicionalno bi bilo izuzetno teško usporediti, recimo, stil i sadržaj novinskih članaka s kaotičnim forumskim raspravama. No zahvaljujući tematskom modeliranju (koje je uz pomoć seed riječi ujednačilo konceptualni okvir), autorica je uspjela “prevesti” diskurse na zajednički jezik tema i tako mjeriti njihovu sličnost. Treći esej tako demonstrira metodološku inovaciju i prednost digitalne analize teksta u komparativnoj kulturnoj sociologiji: uspješno je uspoređen “glas institucija” i “glas građana” kroz kvantitativnu analizu velikog broja tekstova. Zaključak je da u vremenima velikih društvenih izazova (poput migracijske krize) može doći do približavanja različitih diskursnih arena što sugerira kolektivnu usklađenost značenja kada je društvo suočeno s istim izazovom.

**Četvrti esej: Svakodnevni interesi i političke preferencije na društvenim mrežama**

Posljednji esej usredotočuje se na individue u višestranačkom političkom kontekstu Švedske i istražuje kako se njihovi svakodnevni interesi povezuju s političkim preferencijama. Pitanje glasi: da li se i kako “nepolitički” interesi i teme kojima se ljudi bave u svakodnevnom online životu grupiraju i povezani su s njihovim političkim opredjeljenjima? Ideja je da prosječan građanin online pokazuje interese u raznim područjima (npr. sport, glazba, tehnologija, kuhanje) pa se postavlja pitanje može li se iz obrasca tih interesa nazrijeti njegova politička sklonost (lijevo, desno, određena stranka) – odnosno postoji li kulturna podloga političke polarizacije čak i u sferama koje nisu izravno političke.

Za ovaj esej iskorišteni su Twitter podaci o korisnicima u Švedskoj tijekom desetljeća (2010.–2020.). Prikupljene su informacije o tome koje račune i teme ti korisnici prate i o čemu pričaju. Fokus je na korisnicima koji diskutiraju politiku i imigraciju online (dakle politički angažirani), ali se promatra širi spektar njihovih interesa – npr. prati li određeni korisnik Twitter profile vezane uz sport, glazbu, ekonomiju, religiju, humor, itd. i u kojoj mjeri. Tako se dobiva tzv. vektor interesa za svakog korisnika. Uz to, identificirane su političke preferencije korisnika na temelju otvorenih podataka (koga od političara ili stranaka prate na Twitteru, što implicira simpatije prema toj opciji). Švedska s više relevantnih stranaka (lijevih i desnih) pruža zanimljiv kontekst - postoji razlika između ideološke orijentacije (lijevo-desno) i stranačke pripadnosti (koja konkretna stranka).

Koristi se tehnika mješovitog klasteriranja članstva (*mixed-membership clustering*) što je u suštini sličan pristup kao tematsko modeliranje ali primijenjen na korisnike umjesto na riječi. Umjesto “tema” u dokumentima, ovdje se otkrivaju latentne skupine interesa među korisnicima. Svaki korisnik može pripadati pomalo svakoj skupini (poput dokumenata koji mogu sadržavati više tema), ali s različitim stupnjevima – otud “mješovito članstvo”. Ova metoda, primjerice implementirana LDA-modeliranjem gdje su “dokument” = korisnik, a “riječi” = interesi (odnosno praćeni profili/ pojmovi), omogućila je da se izdvoje tipični obrasci interesa. Model je, pojednostavljeno rečeno, grupirao korisnike prema sličnosti u tome koga i što prate: npr. jedna latentna grupa interesa mogla bi se opisati kao “entuzijasti pop-kulture i lifestyle-a”, druga kao “ljubitelji sporta i automobila”, treća “praćenje ekonomije i znanosti”, četvrta “vjerski i obiteljski sadržaji” itd. – ovako zamišljene grupe otkrivene su iz podataka bez prethodnog etiketiranja.

Za svaku od otkrivenih skupina interesa zatim je analizirano kako je povezana s političkom orijentacijom korisnika. Rezultati su vrlo informativni: pokazalo se da se fragmentacija svakodnevnih interesa itekako poklapa s ideološkim podjelama. Primjerice, korisnici čiji interesi čine jedan specifičan klaster često su se pokazali pretežno naklonjeni jednoj političkoj opciji. U Švedskoj se ispostavilo da skupine interesa više odgovaraju lijevo-desnim ideološkim blokovima nego pojedinačnim strankama. To znači da, recimo, dvije različite stranke lijevog centra imaju dosta preklapajuću bazu interesa među svojim simpatizerima (kulturno su slični), dok su simpatizeri jedne lijeve i jedne desne stranke kulturno vrlo različiti u svakodnevnim navikama praćenja sadržaja. Polarizacija je dakle vidljiva i u sferi pop-kulture: ljudi skloni lijevim idejama konzumiraju drugačiji skup medija i sadržaja nego oni skloni desnima. Ipak, identificirano je i nekoliko “preklapajućih” interesa – područja koja zanimaju ljude neovisno o ideologiji. Takvi interesi (primjerice određeni sport ili univerzalna zabava) predstavljaju potencijalne zone dijaloga jer okupljaju ljude različitih političkih uvjerenja na zajedničkom terenu.

Primjena analize teksta (i općenito digitalnih podataka) ovdje je omogućila nove uvide u društvenu polarizaciju. Umjesto uobičajenog anketnog ispitivanja “što voliš raditi u slobodno vrijeme i za koga ćeš glasati”, analizom stvarnih digitalnih tragova (koga ljudi prate i što čitaju) otkriveni su implicitni obrasci koji povezuju kulturu i politiku. To pokazuje snagu ove metode: nenametljivo mapiranje kulturnih podjela u društvu. Zaključak četvrtog eseja je da se politički podijeljena scena odražava i na naizgled apolitičnim životnim sferama pri čemu zajednički interesi mogu ponuditi mostove preko političkog jaza.

## Prednosti računalne analize teksta u istraživanju kulturnih promjena

Ova disertacija ilustrira nekoliko ključnih prednosti primjene računalne analize teksta u društvenim znanostima:

- **Obrada velike količine podataka:** Tradicionalne kvalitativne metode ne bi mogle zahvatiti milijune online postova ili tisuće članaka, no računalna analiza teksta omogućuje analizu golemih korpusa brzo i dosljedno. To znači da se kulturni obrasci mogu detektirati statistički pouzdano, umjesto na temelju ograničenih uzoraka. U radu Menshikove, to je značilo da su zaključci o promjeni diskursa utemeljeni na cjelovitim populacijama tekstova (npr. svi relevantni forum postovi kroz desetljeće) umjesto na nekoliko odabranih slučajeva.

- **Povezivanje mikro i makro razine:** Korištenjem tekstualnih podataka na razini pojedinaca (poput postova pojedinih korisnika foruma ili aktivnosti pojedinih korisnika Twittera), moguće je praćenje ponašanja i promjena kod istih subjekata kroz vrijeme. Zatim se te mikro-informacije mogu agregirati u makro-mjere (opći ton diskursa, frekvencije tema) i statistički rastaviti doprinos različitih mehanizama. Time se ostvaruje preciznije objašnjenje društvenih promjena: znamo kako i zašto je do neke promjene došlo, a ne samo da se ona dogodila.

- **Integracija s teorijom:** Seeded tematsko modeliranje demonstrira kako kvantitativna analiza teksta može biti usmjerena teorijom. Istraživač definira konceptualne kategorije od interesa (npr. interpretacije imigracije kao kultura/ sigurnost/ ekonomija) i zatim koristi podatke da ih operacionalizira i kvantificira. Ova sinteza deduktivnog i induktivnog pristupa povećava relevantnost nalaza – rezultati direktno odgovaraju na teorijska pitanja, ali su i otvoreni za neočekivane obrasce (npr. model može otkriti novu temu koju istraživač nije anticipirao, što se može dalje teorijski interpretirati).

- **Usporedba različitih društvenih sfera:** Jedna od velikih prednosti računalne analize teksta je mogućnost usporedne analize diskursa iz različitih izvora. U ovom istraživanju to je omogućilo da se sagledaju međusobne međuovisnosti između, primjerice, medijskog diskursa i diskursa na društvenim mrežama. Pokazalo se da se ti diskursi mogu konvergirati ili divergirati ovisno o kontekstu što je važan uvid u društvenu rezonanciju događaja (od medija do građana i obratno).

- **Kombinacija s drugim metodama:** Autorica je demonstrirala kako se analiza teksta može kombinirati s eksperimentalnim dizajnima i anketama kako bi se dobila dublja objašnjenja. U drugom eseju, na primjer, računalna analiza medijskih sadržaja poslužila je za precizno mjerenje kontekstualne varijable u eksperimentu (razina medijske pažnje) što bi inače bilo teško ostvarivo. Takva multimodalna metodologija pojačava pouzdanje u zaključke jer ih potkrepljuje iz više kutova (npr. i kvantitativno i kvalitativno).

Naravno, računalna analiza teksta ima i svoje izazove – zahtijeva tehničku stručnost, rad na čišćenju i pripremi podataka, pažnju na valjanost mjera (npr. jesu li otkrivene “teme” uistinu ono što mislimo da jesu) te svijest o etičkim aspektima. Menshikova u radu i to adresira, primjerice, pažljivim pristupom privatnosti (anonimizacija korisničkih imena s foruma, poštivanje uvjeta korištenja platformi), kao i diskusijom ograničenja svakog skupa podataka.

## Zaključak i širi značaj

Kroz četiri studije, Anastasija Menshikova pokazala je kako računalna analiza teksta u R-u može uspješno odgovoriti na složena sociološka pitanja o kulturnim promjenama. Disertacija demonstrira da se velikim tekstualnim podacima može pristupiti znanstveno rigorozno i teorijski informirano čime se produbljuje naše razumijevanje društvenih procesa. Autorica je iz svojih analiza izvukla zaključke da kulturne promjene u javnom diskursu nastaju iz kombinacije mikro-promjena ponašanja i makro-društvenih utjecaja da medijski šum ne mora nužno mijenjati srca i umove ljudi preko noći, da se “elite” i “masa” diskursi mogu približiti kada dijele zajedničko iskustvo te da i u naizgled apolitičnim interesima leže obrasci polarizacije ali i potencijal za povezivanje.

Ova istraživačka priča uči nas da analiza teksta u R-u nije samo tehnička egzibicija već moćan alat za interdisciplinarna istraživanja. U sociologiji (ali i politologiji, komunikologiji, pa i povijesti ili lingvistici), sličan pristup može se koristiti za proučavanje raznih pojava: od načina na koji se oblikuje javna debata o klimatskim promjenama, preko evolucije medijskog diskursa o pandemiji, do usporedbe retorike političara i reakcija građana. Ključna snaga leži u tome da možemo kvantificirati kulturu – mjeriti riječi, teme, sentimente – a da pritom ne izgubimo iz vida kvalitativni značaj tih riječi u društvenom kontekstu.

Menshikovin rad pokazuje kako se računalna obrada teksta (uz pomoć programskog jezika R) može upregnuti za testiranje kompleksnih društvenih teorija o međuovisnostima unutar javnog diskursa. Time se otvaraju vrata za slična istraživanja u budućnosti: svaki put kada postoji velika količina tekstualnih podataka koji odražavaju ljudsko mišljenje, vrijednosti ili interakcije, možemo primijeniti ove metode da iz kaosa riječi izvučemo smislene obrasce. Tako se, konačno, i u hrvatskom kontekstu mogu istraživati pitanja poput kulturnih promjena u medijima i na društvenim mrežama, polarizacije javnosti ili učinaka kriznih događaja na javni diskurs, a sve to pomoću pametne primjene analize teksta i domašaja računalne snage u službi znanosti.
