<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="hr" xml:lang="hr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Tokenizacijom teksta, uklanjanjem zaustavnih riječi i lematizacijom ispunjene su temeljne pretpostavke za analizu teksta, koja se sada može provesti na dobivenom podatkovnom okviru. Sljedeći korak je jednostavna deskriptivna analiza teksta. Riječ je o najjednostavnijem obliku analize teksta, koji se svodi na brojanje riječi, izračun njihove relativne učestalosti i korelaciju učestalosti riječi među različitim tekstovima. Iako su informacije koje takva analiza daje razmjerno jednostavne, ona je važan početni korak u upoznavanju s tekstom i radu s njim.">

<title>8&nbsp; Deskriptivna analiza teksta – Analiza teksta u R-u</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./3_2_analiza_učestalosti_riječi.html" rel="next">
<link href="./3_0_DESKRIPTIVNA_ANALIZA_TEKSTA.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ed937027807105842f1b8e9a1d8c8bec.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
background: #8B475D;
      }
</style>


<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./3_0_DESKRIPTIVNA_ANALIZA_TEKSTA.html">DESKRIPTIVNA ANALIZA TEKSTA</a></li><li class="breadcrumb-item"><a href="./3_1_deskriptivna_analiza_teksta.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Deskriptivna analiza teksta</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./3_0_DESKRIPTIVNA_ANALIZA_TEKSTA.html">DESKRIPTIVNA ANALIZA TEKSTA</a></li><li class="breadcrumb-item"><a href="./3_1_deskriptivna_analiza_teksta.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Deskriptivna analiza teksta</span></a></li></ol></nav>
      <h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Deskriptivna analiza teksta</span></h1>
                  <div>
        <div class="description">
          Tokenizacijom teksta, uklanjanjem zaustavnih riječi i lematizacijom ispunjene su temeljne pretpostavke za analizu teksta, koja se sada može provesti na dobivenom podatkovnom okviru. Sljedeći korak je jednostavna deskriptivna analiza teksta. Riječ je o najjednostavnijem obliku analize teksta, koji se svodi na brojanje riječi, izračun njihove relativne učestalosti i korelaciju učestalosti riječi među različitim tekstovima. Iako su informacije koje takva analiza daje razmjerno jednostavne, ona je važan početni korak u upoznavanju s tekstom i radu s njim.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analiza teksta u R-u</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/alen-hu" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Predgovor</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./1_0_UVOD U ANALIZU TEKSTA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">UVOD U ANALIZU TEKSTA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_1_uvod_u_analizu_teksta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Uvod u analizu teksta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_2_primjena_analize_teksta_u_znanstvenim_istraživanjima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Primjena analize teksta u znanstvenim istraživanjima</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./2_0_POČETAK U RADU S TEKSTOM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">POČETAK U RADU S TEKSTOM</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_1_tekstualni_nizovi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Tekstualni nizovi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_2_regularni_izrazi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regularni izrazi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_3_učitavanje_i_oblikovanje_podataka.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Učitavanje i oblikovanje podataka</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_4_pretpostavke_za_analizu_teksta_u_tidytext-u.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pretpostavke za analizu teksta u tidytext-u</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./3_0_DESKRIPTIVNA_ANALIZA_TEKSTA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DESKRIPTIVNA ANALIZA TEKSTA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_1_deskriptivna_analiza_teksta.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Deskriptivna analiza teksta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_2_analiza_učestalosti_riječi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza učestalosti riječi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_3_odnosi_među_riječima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Odnosi među riječima</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./4_0_ANALIZA_SENTIMENATA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANALIZA SENTIMENATA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_1_analiza_sentimenata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analiza sentimenata</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./5_0_TEKSTUALNA_MODELIRANJA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TEKSTUALNA MODELIRANJA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5_1_tematsko_modeliranje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Tematsko modeliranje</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./6_0_DODATNE_MOGUĆNOSTI_RADA_S_TEKSTOM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DODATNE MOGUĆNOSTI RADA S TEKSTOM</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6_1_rad_s_neurednim_podacima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Rad s neurednim podacima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6_2_vizualizacije_teksta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vizualizacija teksta</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatura</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="3">
    <h2 id="toc-title">Sadržaj poglavlja</h2>
   
  <ul>
  <li><a href="#brojanje-riječi" id="toc-brojanje-riječi" class="nav-link active" data-scroll-target="#brojanje-riječi"><span class="header-section-number">8.1</span> Brojanje riječi</a></li>
  <li><a href="#relativna-učestalost-riječi" id="toc-relativna-učestalost-riječi" class="nav-link" data-scroll-target="#relativna-učestalost-riječi"><span class="header-section-number">8.2</span> Relativna učestalost riječi</a>
  <ul class="collapse">
  <li><a href="#korelacija-relativnih-učestalosti" id="toc-korelacija-relativnih-učestalosti" class="nav-link" data-scroll-target="#korelacija-relativnih-učestalosti"><span class="header-section-number">8.2.1</span> Korelacija relativnih učestalosti</a></li>
  </ul></li>
  </ul>
<div class="quarto-other-links"><h2>Other Links</h2><ul><li><a href="ahusnjak0810@gmail.com"><i class="bi bi-chat-text"></i>Gmail</a></li><li><a href="www.linkedin.com/in/alen-husnjak-5a0bb9206"><i class="bi bi-linkedin"></i>LinkedIn</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="brojanje-riječi" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="brojanje-riječi"><span class="header-section-number">8.1</span> Brojanje riječi</h2>
<p>Najjednostavnija analiza teksta je brojanje koliko se puta pojedina riječ pojavljuje u tekstu. Takva se analiza provodi na tokenima, odnosno na riječima ili drugim jedinicama na koje je tekst podijeljen.</p>
<p>Pritom možemo brojati riječi u obliku u kojem se pojavljuju u tekstu ili njihove lematizirane oblike, odnosno rječničke oblike. Riječi u izvornom obliku bolje je brojati kad nas zanima kako je tekst napisan jer one čuvaju gramatičke oblike poput broja (jednina ili množina) ili glagolskog vremena. Tada su, primjerice, <em>brother</em> i <em>brothers</em> dvije različite riječi pa možemo vidjeti govori li tekst češće o jednom bratu ili o braći. Lematizirane je oblike bolje brojati kad nas zanima o čemu tekst govori jer se tada svi oblici iste riječi broje zajedno, odnosno, <em>brother</em> i <em>brothers</em> ubrajaju se u istu riječ, <em>brother</em>.</p>
<p>Brojanje se provodi funkcijom <code>count()</code> iz paketa <code>dplyr</code>. Argument <code>sort = TRUE</code> slaže rezultat od najčešće prema najrjeđoj riječi.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Brojanje riječi u izvornom obliku</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>tToBtB_word_tokens_stop_words_lemmatize <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(word, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,247 × 2
   word          n
   &lt;chr&gt;     &lt;int&gt;
 1 king         33
 2 charlatan    27
 3 pot          23
 4 wizard       22
 5 death        20
 6 wand         20
 7 witch        20
 8 babbitty     17
 9 heart        17
10 magic        17
# ℹ 1,237 more rows</code></pre>
</div>
</div>
<p>Ispis prikazuje sve riječi koje se pojavljuju u bajkama, ukupno njih 1247 različitih, i koliko se puta svaka od njih pojavljuje. Najčešća je riječ <em>king</em> (33 pojavljivanja), a slijede <em>charlatan</em> (27), <em>pot</em> (23) i <em>wizard</em> (22). Riječi <em>death</em>, <em>wand</em> i <em>witch</em> pojavljuju se jednako često, po 20 puta. Već i ovakav jednostavan popis dobro odražava sadržaj knjige. Među najčešćim riječima nalaze se likovi i predmeti oko kojih se vrte pojedine bajke, poput lonca (<em>pot</em>) iz bajke <em>The Wizard and the Hopping Pot</em> ili imena <em>Babbitty</em> (17) iz bajke <em>Babbitty Rabbitty and Her Cackling Stumps</em>, te riječi poput <em>magic</em>, <em>wizard</em> i <em>witch</em>, koje upućuju na čarobni svijet u kojem se bajke odvijaju.</p>
<p>Ako brojimo lematizirane oblike, rezultat se mijenja.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Brojanje lematiziranih riječi</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>tToBtB_word_tokens_stop_words_lemmatize <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(lemma, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,076 × 2
   lemma         n
   &lt;chr&gt;     &lt;int&gt;
 1 king         33
 2 witch        32
 3 charlatan    27
 4 wand         25
 5 wizard       24
 6 pot          23
 7 brother      22
 8 death        20
 9 heart        18
10 babbitty     17
# ℹ 1,066 more rows</code></pre>
</div>
</div>
<p>Brojanjem lema broj različitih riječi smanjio se s 1247 na 1076 jer su se različiti oblici iste riječi spojili u jednu lematiziranu. Promijenio se i redoslijed najčešćih riječi. Najviše se ističe riječ <em>witch</em> koja se kao lema pojavljuje 32 puta, dok se u izvornom obliku pojavljivala 20 puta. Slično tome, lema <em>brother</em> pojavljuje se 22 puta i nalazi se među deset najčešćih, iako riječ <em>brother</em> u izvornom obliku među njima nije bila. To znači da se znatan dio pojavljivanja tih riječi odnosi na njihove druge oblike, najčešće na množinu. Koji su to oblici, možemo provjeriti tako da funkcijom <code>filter()</code> iz paketa <code>dplyr</code> zadržimo samo retke s određenom lematiziranom riječju i zatim prebrojimo riječi u izvornom obliku.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Oblici u kojima se pojavljuje lematizirana riječ "brother"</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>tToBtB_word_tokens_stop_words_lemmatize <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(lemma <span class="sc">==</span> <span class="st">"brother"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(word, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  word         n
  &lt;chr&gt;    &lt;int&gt;
1 brother     15
2 brothers     7</code></pre>
</div>
</div>
<p>Ovakvi su ispisi korisni za rad, ali nisu pregledni za predstavljanje rezultata. Zato je rezultate bolje prikazati grafički, paketom <code>ggplot2</code>. Funkcija <code>slice_max()</code> zadržava deset najčešćih riječi, a <code>fct_reorder()</code> slaže riječi na osi y prema broju pojavljivanja, kako bi najčešća riječ bila na vrhu.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafički prikaz deset najčešćih lematiziranih riječi</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>tToBtB_word_tokens_stop_words_lemmatize <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(lemma, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(n, <span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> <span class="fu">fct_reorder</span>(lemma, n))) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Broj pojavljivanja u bajkama"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Lematizirana riječ"</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="3_1_deskriptivna_analiza_teksta_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Uzmimo sada širi primjer svih bajki braće Bardea Bedlea. Brojanje riječi tako možemo provesti i za svaku bajku zasebno. Za to funkciji <code>count()</code> uz lematiziranu riječ navodimo i stupac <code>fairy_tale</code> pa se riječi broje unutar svake bajke.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Brojanje lema po bajkama</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>tToBtB_word_tokens_stop_words_lemmatize <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(fairy_tale, lemma, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,421 × 3
   fairy_tale                                  lemma         n
   &lt;chr&gt;                                       &lt;chr&gt;     &lt;int&gt;
 1 4_babbitty_rabbitty_and_her_cackling_stumps king         33
 2 4_babbitty_rabbitty_and_her_cackling_stumps charlatan    27
 3 1_the_wizard_and_the_hopping_pot            pot          23
 4 5_the_tale_of_the_three_brothers            brother      22
 5 4_babbitty_rabbitty_and_her_cackling_stumps witch        19
 6 5_the_tale_of_the_three_brothers            death        18
 7 4_babbitty_rabbitty_and_her_cackling_stumps babbitty     17
 8 2_the_fountain_of_fair_fortune              fountain     16
 9 1_the_wizard_and_the_hopping_pot            wizard       15
10 3_the_warlocks_hairy_heart                  heart        14
# ℹ 1,411 more rows</code></pre>
</div>
</div>
<p>Najčešće riječi u svakoj bajci najpreglednije je prikazati u zasebnim grafovima, funkcijom <code>facet_wrap()</code>. Budući da je redoslijed riječi u svakoj bajci drugačiji, za slaganje riječi unutar svakog grafa koriste se funkcije <code>reorder_within()</code> i <code>scale_y_reordered()</code> iz paketa <code>tidytext</code>. Funkcija <code>slice_max()</code> pritom zadržava osam najčešćih riječi u svakoj bajci. Ako više riječi ima jednak broj pojavljivanja, prikazuju se sve pa neki grafovi mogu imati više od osam riječi.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafički prikaz najčešćih lema po bajkama</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>tToBtB_word_tokens_stop_words_lemmatize <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(fairy_tale, lemma, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fairy_tale) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(n, <span class="at">n =</span> <span class="dv">8</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> <span class="fu">reorder_within</span>(lemma, n, fairy_tale), <span class="at">fill =</span> fairy_tale)) <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>fairy_tale, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_reordered</span>() <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Broj pojavljivanja"</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Lematizirana riječ"</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Najčešće riječi u svakoj bajci"</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="3_1_deskriptivna_analiza_teksta_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Konačno, može nas zanimati i neka određena riječ, primjerice <em>wand</em>, te u kojim se bajkama i koliko često pojavljuje.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Učestalost riječi "wand" po bajkama</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>tToBtB_word_tokens_stop_words_lemmatize <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(fairy_tale, lemma) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(lemma <span class="sc">==</span> <span class="st">"wand"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  fairy_tale                                  lemma     n
  &lt;chr&gt;                                       &lt;chr&gt; &lt;int&gt;
1 1_the_wizard_and_the_hopping_pot            wand      1
2 2_the_fountain_of_fair_fortune              wand      3
3 3_the_warlocks_hairy_heart                  wand      3
4 4_babbitty_rabbitty_and_her_cackling_stumps wand     10
5 5_the_tale_of_the_three_brothers            wand      8</code></pre>
</div>
</div>
<p>Lema <em>wand</em> pojavljuje se u svih pet bajki, ukupno 25 puta, ali vrlo neravnomjerno. Najčešća je u bajci <em>Babbitty Rabbitty and Her Cackling Stumps</em> (10 pojavljivanja) i u bajci <em>The Tale of the Three Brothers</em> (8), dok se u bajkama <em>The Fountain of Fair Fortune</em> i <em>The Warlock’s Hairy Heart</em> pojavljuje po tri puta, a u bajci <em>The Wizard and the Hopping Pot</em> samo jednom. Pritom treba imati na umu da su bajke različite duljine pa apsolutni broj pojavljivanja ne govori nužno koliko je neka riječ važna u pojedinoj bajci. Zato ćemo u sljedećem odjeljku bajke usporediti prema relativnoj učestalosti riječi.</p>
</section>
<section id="relativna-učestalost-riječi" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="relativna-učestalost-riječi"><span class="header-section-number">8.2</span> Relativna učestalost riječi</h2>
<p>Broj pojavljivanja riječi ovisi i o duljini teksta jer se u duljoj se bajci gotovo svaka riječ pojavljuje češće. Zato je bajke bolje uspoređivati prema <strong>relativnoj učestalosti</strong>, odnosno udjelu pojedine riječi u ukupnom broju riječi u bajci.</p>
<p>Relativna se učestalost računa u nekoliko koraka:</p>
<ol type="1">
<li><p>Iz podataka uklanjamo tokene koji nisu riječi, poput brojeva. Funkcija <code>str_detect()</code> s uzorkom <code>"^[a-z']+$"</code> zadržava samo one leme koje se od početka (<code>^</code>) do kraja (<code>$</code>) sastoje isključivo od malih slova i apostrofa.</p></li>
<li><p>Funkcijom <code>count()</code> brojimo pojavljivanja svake leme u svakoj bajci.</p></li>
<li><p>Podatke grupiramo prema bajci i za svaku lemu računamo udio u ukupnom broju riječi u toj bajci (<code>n / sum(n)</code>).</p></li>
<li><p>Uklanjamo apsolutni broj pojavljivanja i slažemo leme od najveće prema najmanjoj relativnoj učestalosti.</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>tToBtB_frequency <span class="ot">&lt;-</span> tToBtB_word_tokens_stop_words_lemmatize <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Zadržavanje lema koje se sastoje samo od slova i apostrofa (bez brojeva)</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(lemma, <span class="st">"^[</span><span class="sc">\\</span><span class="st">p{L}']+$"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Broj pojavljivanja svake leme u svakoj bajci</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(fairy_tale, lemma) <span class="sc">|&gt;</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Grupiranje prema bajci</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fairy_tale) <span class="sc">|&gt;</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Udio leme u ukupnom broju riječi u bajci</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Uklanjanje apsolutnog broja pojavljivanja</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>n) <span class="sc">|&gt;</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Slaganje od najveće prema najmanjoj relativnoj učestalosti</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(proportion))</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Pregled</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>tToBtB_frequency</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,421 × 3
   fairy_tale                                  lemma     proportion
   &lt;chr&gt;                                       &lt;chr&gt;          &lt;dbl&gt;
 1 5_the_tale_of_the_three_brothers            brother       0.0982
 2 5_the_tale_of_the_three_brothers            death         0.0804
 3 1_the_wizard_and_the_hopping_pot            pot           0.0561
 4 4_babbitty_rabbitty_and_her_cackling_stumps king          0.0482
 5 4_babbitty_rabbitty_and_her_cackling_stumps charlatan     0.0395
 6 1_the_wizard_and_the_hopping_pot            wizard        0.0366
 7 5_the_tale_of_the_three_brothers            wand          0.0357
 8 3_the_warlocks_hairy_heart                  heart         0.0317
 9 3_the_warlocks_hairy_heart                  warlock       0.0294
10 4_babbitty_rabbitty_and_her_cackling_stumps witch         0.0278
# ℹ 1,411 more rows</code></pre>
</div>
</div>
<p>Rezultat je tablica s 1421 retkom u kojoj svaki redak sadrži relativnu učestalost jedne lematizirane riječi u jednoj bajci. Najveću relativnu učestalost ima riječ <em>brother</em> u bajci <em>The Tale of the Three Brothers</em> (0,0982), a u istoj je bajci na drugom mjestu lema <em>death</em> (0,0804). Slijede <em>pot</em> u bajci <em>The Wizard and the Hopping Pot</em> (0,0561) te <em>king</em> (0,0482) i <em>charlatan</em> (0,0395) u bajci <em>Babbitty Rabbitty and Her Cackling Stumps</em>. U bajci <em>The Warlock’s Hairy Heart</em> najistaknutije su riječi <em>heart</em> (0,0317) i <em>warlock</em> (0,0294). Najčešće riječi u svakoj bajci uglavnom su upravo one koje se pojavljuju i u njezinu naslovu, a što pokazuje da relativna učestalost dobro izdvaja središnje teme pojedine bajke. Jedino se bajka <em>The Fountain of Fair Fortune</em> ne pojavljuje među deset najviših vrijednosti pa se njezin rječnik čini ravnomjernije raspoređenim, bez jedne riječi koja bi se izrazito isticala.</p>
<p>Pritom je važno ispravno protumačiti relativnu učestalost. Vrijednost 0,0982 za lemu <em>brother</em> u bajci <em>The Tale of the Three Brothers</em> znači da ta riječ čini 9,82 % svih riječi u bajci, nakon uklanjanja zaustavnih riječi. Drugim riječima, otprilike je svaka deseta riječ u toj bajci <em>brother</em>. To je i očekivano jer se priča vrti oko trojice braće, a ista je bajka i najbolji primjer zašto apsolutni i relativni broj ne moraju dati isti poredak. Lema <em>wand</em> pojavljuje se u bajci <em>Babbitty Rabbitty and Her Cackling Stumps</em> češće nego u bajci <em>The Tale of the Three Brothers</em> (10 prema 8 puta). Ipak, u bajci <em>The Tale of the Three Brothers</em> ima relativnu učestalost 0,0357 i nalazi se među deset najviših vrijednosti, dok u bajci <em>Babbitty Rabbitty</em> među njima nije. Budući da je <em>The Tale of the Three Brothers</em> kraća bajka, isti broj pojavljivanja u njoj čini veći udio svih riječi.</p>
<p>Može nas zanimati i frekvencija pojedinih riječi u različitim bajkama što možemo jednostavnije vidjeti filtriranjem pojedine riječi, primjerice riječi <em>wand</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Relativna učestalost riječi "wand" po bajkama</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>tToBtB_frequency <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(lemma <span class="sc">==</span> <span class="st">"wand"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  fairy_tale                                  lemma proportion
  &lt;chr&gt;                                       &lt;chr&gt;      &lt;dbl&gt;
1 5_the_tale_of_the_three_brothers            wand     0.0357 
2 4_babbitty_rabbitty_and_her_cackling_stumps wand     0.0146 
3 3_the_warlocks_hairy_heart                  wand     0.00679
4 2_the_fountain_of_fair_fortune              wand     0.00514
5 1_the_wizard_and_the_hopping_pot            wand     0.00244</code></pre>
</div>
</div>
<p>Ovdje su vidljive razlike među bajkama. Riječ <em>wand</em> ima najveću relativnu učestalost u bajci <em>The Tale of the Three Brothers</em> (0,0357) u kojoj čini oko 3,6 % svih riječi. Slijedi bajka <em>Babbitty Rabbitty and Her Cackling Stumps</em> (0,0146), a znatno je manja u bajkama <em>The Warlock’s Hairy Heart</em> (0,0068), <em>The Fountain of Fair Fortune</em> (0,0051) i <em>The Wizard and the Hopping Pot</em> (0,0024). U bajci <em>The Tale of the Three Brothers</em> riječ <em>wand</em> relativno je gotovo dva i pol puta češća nego u bajci <em>Babbitty Rabbitty</em>, iako se u njoj pojavljuje rjeđe (8 prema 10 puta). Razlog je u duljini bajki. Iz broja pojavljivanja i relativne učestalosti može se procijeniti da <em>The Tale of the Three Brothers</em> ima oko 220 riječi (nakon uklanjanja zaustavnih riječi), a <em>Babbitty Rabbitty</em> oko 680, odnosno otprilike tri puta više. Isti broj pojavljivanja u kraćoj bajci zato čini veći udio. Upravo zbog toga se bajke različite duljine bolje uspoređuju prema relativnoj nego prema apsolutnoj učestalosti.</p>
<p>Relativne učestalosti svih riječi u dvjema bajkama najpreglednije je usporediti dijagramom raspršenja. Kao referentnu bajku uzet ćemo <em>The Tale of the Three Brothers</em> i s njom usporediti svaku od ostalih bajki. Za to podatke najprije treba preoblikovati:</p>
<ol type="1">
<li><p>Funkcijom <code>pivot_wider()</code> podatke pretvaramo u široki oblik u kojem je svaka bajka zaseban stupac, a svaki redak jedna lema. Tako su relativne učestalosti iste leme u različitim bajkama u istom retku.</p></li>
<li><p>Funkcijom <code>pivot_longer()</code> ostale četiri bajke vraćamo u dugi oblik, dok stupac referentne bajke ostaje zaseban. Svaki redak tada sadrži riječ, njezinu relativnu učestalost u referentnoj bajci i njezinu relativnu učestalost u jednoj od ostalih bajki.</p></li>
<li><p>Uklanjamo retke u kojima neka od dviju vrijednosti nedostaje (<code>NA</code>), odnosno riječi koje se ne pojavljuju u objema bajkama.</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Priprema podataka za usporedbu s bajkom The Tale of the Three Brothers</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>tToBtB_frequency_compare <span class="ot">&lt;-</span> tToBtB_frequency <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Svaka bajka postaje zaseban stupac</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> fairy_tale, <span class="at">values_from =</span> proportion) <span class="sc">|&gt;</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ostale bajke vraćaju se u dugi oblik, referentna bajka ostaje stupac</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">-</span><span class="fu">c</span>(lemma, <span class="st">`</span><span class="at">5_the_tale_of_the_three_brothers</span><span class="st">`</span>),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"fairy_tale"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"proportion"</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Zadržavanje lema koje se pojavljuju u objema bajkama</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(proportion), <span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">5_the_tale_of_the_three_brothers</span><span class="st">`</span>))</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Pregled</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>tToBtB_frequency_compare</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 136 × 4
   lemma  `5_the_tale_of_the_three_brothers` fairy_tale               proportion
   &lt;chr&gt;                               &lt;dbl&gt; &lt;chr&gt;                         &lt;dbl&gt;
 1 death                             0.0804  1_the_wizard_and_the_ho…    0.00244
 2 death                             0.0804  2_the_fountain_of_fair_…    0.00171
 3 wizard                            0.0134  1_the_wizard_and_the_ho…    0.0366 
 4 wizard                            0.0134  4_babbitty_rabbitty_and…    0.00877
 5 wand                              0.0357  1_the_wizard_and_the_ho…    0.00244
 6 wand                              0.0357  4_babbitty_rabbitty_and…    0.0146 
 7 wand                              0.0357  3_the_warlocks_hairy_he…    0.00679
 8 wand                              0.0357  2_the_fountain_of_fair_…    0.00514
 9 magic                             0.00446 1_the_wizard_and_the_ho…    0.00732
10 magic                             0.00446 4_babbitty_rabbitty_and…    0.0161 
# ℹ 126 more rows</code></pre>
</div>
</div>
<p>Tablica ima 136 redaka. Svaki redak sadrži jednu riječ, njezinu relativnu učestalost u bajci <em>The Tale of the Three Brothers</em> i njezinu relativnu učestalost u jednoj od ostalih bajki. Riječ <em>wand</em>, primjerice, pojavljuje se u četiri retka, po jednom za svaku bajku s kojom se uspoređuje, a u svakom je retku njezina vrijednost u bajci <em>The Tale of the Three Brothers</em> ista (0,0357). U tablici su samo riječi koje se pojavljuju u obje bajke pa riječi karakteristične samo za jednu bajku u usporedbi ne sudjeluju.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dijagram raspršenja relativnih učestalosti</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  tToBtB_frequency_compare,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> proportion, <span class="at">y =</span> <span class="st">`</span><span class="at">5_the_tale_of_the_three_brothers</span><span class="st">`</span>, <span class="at">color =</span> fairy_tale)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Dijagonala kao referentna crta</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">color =</span> <span class="st">"gray40"</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Točke s malim nasumičnim pomakom, kako se ne bi preklapale</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">height =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Natpisi s lemama</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> lemma), <span class="at">check_overlap =</span> <span class="cn">TRUE</span>, <span class="at">vjust =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Logaritamske skale s postocima</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">labels =</span> <span class="fu">percent_format</span>()) <span class="sc">+</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> <span class="fu">percent_format</span>()) <span class="sc">+</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Zaseban graf za svaku bajku</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>fairy_tale, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Sakrivanje legende</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Nazivi osi</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"The Tale of the Three Brothers"</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="3_1_deskriptivna_analiza_teksta_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Uzmimo za primjer riječ <em>wizard</em> i graf za bajku <em>The Wizard and the Hopping Pot</em>. U tablici za tu lemu i bajku stoje dvije vrijednosti, u bajci <em>The Wizard and the Hopping Pot</em> riječ čini 3,66 % riječi, a u bajci <em>The Tale of the Three Brothers</em> 1,34 %. Prva vrijednost određuje položaj točke na osi x, a druga na osi y. Točku zato tražimo desno na osi x (oko 3,7 %) i nisko na osi y (oko 1,3 %). Položaj ispod dijagonale znači da je riječ relativno češća u bajci na osi x nego u bajci na osi y. Koliko je češća, dobivamo dijeljenjem dviju vrijednosti: 3,66 / 1,34 ≈ 2,7. Riječ <em>wizard</em> je, dakle, u bajci <em>The Wizard and the Hopping Pot</em> relativno gotovo tri puta češća nego u bajci <em>The Tale of the Three Brothers</em>, a što je i očekivano jer je čarobnjak glavni lik te bajke.</p>
<p>Suprotan primjer je lema <em>death</em> na istom grafu. U bajci <em>The Wizard and the Hopping Pot</em> čini samo 0,24 % riječi, a u bajci <em>The Tale of the Three Brothers</em> 8,04 % pa se točka nalazi lijevo i visoko, daleko iznad dijagonale. Omjer 8,04 / 0,24 ≈ 33 znači da je smrt u bajci o trojici braće relativno tridesetak puta češća tema. Točka bliže dijagonali je riječ <em>wand</em> na grafu za bajku <em>Babbitty Rabbitty and Her Cackling Stumps</em>, 1,46 % na osi x i 3,57 % na osi y. Nalazi se iznad dijagonale, ali bliže njoj nego <em>death</em> jer je omjer manji (3,57 / 1,46 ≈ 2,4). Štapić je, dakle, važan predmet u obje bajke, iako je u bajci o trojici braće relativno nešto češći. Na grafu za istu bajku lema <em>magic</em> nalazi se ispod dijagonale (1,61 % prema 0,45 %), pa je magija relativno oko tri i pol puta češća u bajci <em>Babbitty Rabbitty</em>.</p>
<p>Dakle, iz ovih primjera proizlaze tri pravila za čitanje grafa:</p>
<ul>
<li><p>točka na dijagonali znači da riječ ima jednak udio u objema bajkama;</p></li>
<li><p>točka iznad dijagonale znači da je riječ relativno češća u bajci <em>The Tale of the Three Brothers</em>, a točka ispod dijagonale da je češća u bajci navedenoj iznad grafa;</p></li>
<li><p>što je točka dalje od dijagonale, to je razlika veća (budući da obje osi imaju logaritamsku skalu, jednaka udaljenost od dijagonale znači jednak omjer, a ne jednaku razliku jer je riječ s udjelima 0,5 % i 1 % jednako udaljena od dijagonale kao riječ s udjelima 2 % i 4 %).</p></li>
</ul>
<p>Gledamo li grafove u cjelini, većina se točaka nalazi iznad dijagonale. To je dijelom posljedica duljine bajki, odnosno da je <em>The Tale of the Three Brothers</em> znatno kraća od ostalih bajki pa svaka riječ koja se u njoj pojavi makar jednom ima udio od najmanje 0,45 %. Zato pri tumačenju treba gledati prije svega točke koje su od dijagonale izrazito udaljene, poput riječi <em>death</em>.</p>
<section id="korelacija-relativnih-učestalosti" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="korelacija-relativnih-učestalosti"><span class="header-section-number">8.2.1</span> Korelacija relativnih učestalosti</h3>
<p>Sličnost dviju bajki po rječniku može se izraziti i brojem, <strong>koeficijentom korelacije relativnih učestalosti</strong>. Primjerice, možemo se pitati koliko su povezane relativne učestalosti riječi u bajkama <em>The Tale of the Three Brothers</em> i <em>The Wizard and the Hopping Pot</em>. Za to se koristi Pearsonov koeficijent korelacije i funkcija <code>cor.test()</code> koja uz koeficijent provodi i test njegove statističke značajnosti.</p>
<p>Ključno je da se pritom uspoređuju relativne učestalosti iste riječi u dvije bajke. Upravo je takav oblik podataka pripremljen u podatkovnom okviru <code>tToBtB_frequency_compare</code> u kojem je u svakom retku jedna riječ, njezina relativna učestalost u bajci <em>The Tale of the Three Brothers</em> (stupac <code>5_the_tale_of_the_three_brothers</code>) i njezina relativna učestalost u jednoj od ostalih bajki (stupac <code>proportion</code>). Postupak zato ima samo dva koraka:</p>
<ol type="1">
<li><p>Funkcijom <code>filter()</code> iz podatkovnog okvira <code>tToBtB_frequency_compare</code> izdvajamo retke za bajku <em>Babbitty Rabbitty and Her Cackling Stumps</em> i spremamo ih u novi objekt <code>babbitty_compare</code>. U njemu su sada samo leme koje se pojavljuju u objema bajkama, a uz svaku stoje njezine dvije relativne učestalosti.</p></li>
<li><p>Funkcijom <code>cor.test()</code> računamo Pearsonov koeficijent korelacije između tih dviju vrijednosti i testiramo njegovu statističku značajnost. Stupce koje uspoređujemo zadajemo formulom <code>~ proportion +</code>5_the_tale_of_the_three_brothers`<code>u kojoj se nazivi stupaca navode iza znaka</code>~<code>i povezuju znakom</code>+<code>. Argumentom</code>data` navodimo podatkovni okvir u kojem se ti stupci nalaze. Budući da naziv drugog stupca počinje brojem, pišemo ga unutar obrnutih jednostrukih navodnika.</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Izdvajanje usporedbe s bajkom Babbitty Rabbitty and Her Cackling Stumps</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>babbitty_compare <span class="ot">&lt;-</span> tToBtB_frequency_compare <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fairy_tale <span class="sc">==</span> <span class="st">"4_babbitty_rabbitty_and_her_cackling_stumps"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Korelacija relativnih učestalosti lema u dvjema bajkama</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> proportion <span class="sc">+</span> <span class="st">`</span><span class="at">5_the_tale_of_the_three_brothers</span><span class="st">`</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> babbitty_compare</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  proportion and 5_the_tale_of_the_three_brothers
t = 3.4845, df = 31, p-value = 0.001494
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.2288827 0.7391884
sample estimates:
      cor 
0.5305059 </code></pre>
</div>
</div>
<p>Koeficijent korelacije iznosi 0,53 što upućuje na umjerenu pozitivnu povezanost relativnih učestalosti riječi u dvjema bajkama. Riječi koje su relativno česte u bajci <em>The Tale of the Three Brothers</em> uglavnom su relativno česte i u bajci <em>Babbitty Rabbitty and Her Cackling Stumps</em> i obrnuto. Na dijagramu raspršenja to se vidi tako što se točke na grafu za bajku <em>Babbitty Rabbitty</em> raspoređuju uz dijagonalu, od donjeg lijevog prema gornjem desnom kutu. Jedan od primjera je lema <em>wand</em> koja je u objema bajkama među relativno češćim riječima (3,57 % i 1,46 %).</p>
<p>Ostale vrijednosti u ispisu govore o tome može li se taj rezultat pripisati slučaju. Vrijednost <code>df = 31</code> broj je stupnjeva slobode koji je kod korelacije jednak broju parova umanjenom za dva pa se korelacija računala na 33 leme zajedničke objema bajkama. T-statistika iznosi 3,48, a p-vrijednost 0,0015. Budući da je p-vrijednost manja od 0,05, najčešće korištenog praga statističke značajnosti, možemo odbaciti nultu hipotezu prema kojoj korelacija ne postoji i zaključiti da je povezanost statistički značajna. P-vrijednost od 0,0015 znači da bi, kad korelacije stvarno ne bi bilo, vjerojatnost dobivanja ovako jake ili jače korelacije samo slučajno iznosila oko 0,15 %.</p>
<p>Kako bismo procijenili koliko je ta procjena precizna, koristimo 95 %-tni interval pouzdanosti koji se proteže od 0,23 do 0,74. Cijeli je interval iznad nule, a što potvrđuje da je povezanost pozitivna, ali je i razmjerno širok. S obzirom na mali broj zajedničkih riječi, stvarna povezanost mogla bi biti i slaba i prilično jaka. Zato rezultat valja tumačiti oprezno jer dvije bajke dijele dio rječnika koji je u objema relativno važan, no na temelju 33 riječi ne možemo precizno reći koliko su po rječniku slične.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./3_0_DESKRIPTIVNA_ANALIZA_TEKSTA.html" class="pagination-link" aria-label="DESKRIPTIVNA ANALIZA TEKSTA">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">DESKRIPTIVNA ANALIZA TEKSTA</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./3_2_analiza_učestalosti_riječi.html" class="pagination-link" aria-label="Analiza učestalosti riječi">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza učestalosti riječi</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, Alen Husnjak</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="./www.linkedin.com/in/alen-husnjak-5a0bb9206">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>