<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="hr" xml:lang="hr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Riječi koje se u tekstu pojavljuju najčešće rijetko su one koje o njemu govore najviše. Učestalost riječi u jeziku podliježe pravilnosti poznatoj kao Zipfov zakon, a prema kojem se malobrojne riječi pojavljuju iznimno često, a velika većina tek rijetko. Zato samo brojanje riječi ne govori koje su riječi za neki tekst doista važne. Odgovor na to pitanje daje mjera tf-idf koja učestalost riječi u jednom tekstu uspoređuje s njezinom prisutnošću u ostalim tekstovima i tako izdvaja riječi po kojima se pojedini tekst razlikuje od ostalih.">

<title>9&nbsp; Analiza učestalosti riječi – Analiza teksta u R-u</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./3_3_odnosi_među_riječima.html" rel="next">
<link href="./3_1_deskriptivna_analiza_teksta.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ed937027807105842f1b8e9a1d8c8bec.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
background: #8B475D;
      }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./3_1_deskriptivna_analiza_teksta.html">3_0_POČETAK U RADU S TEKSTOM.qmd</a></li><li class="breadcrumb-item"><a href="./3_2_analiza_učestalosti_riječi.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza učestalosti riječi</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./3_1_deskriptivna_analiza_teksta.html">3_0_POČETAK U RADU S TEKSTOM.qmd</a></li><li class="breadcrumb-item"><a href="./3_2_analiza_učestalosti_riječi.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza učestalosti riječi</span></a></li></ol></nav>
      <h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza učestalosti riječi</span></h1>
                  <div>
        <div class="description">
          Riječi koje se u tekstu pojavljuju najčešće rijetko su one koje o njemu govore najviše. Učestalost riječi u jeziku podliježe pravilnosti poznatoj kao Zipfov zakon, a prema kojem se malobrojne riječi pojavljuju iznimno često, a velika većina tek rijetko. Zato samo brojanje riječi ne govori koje su riječi za neki tekst doista važne. Odgovor na to pitanje daje mjera tf-idf koja učestalost riječi u jednom tekstu uspoređuje s njezinom prisutnošću u ostalim tekstovima i tako izdvaja riječi po kojima se pojedini tekst razlikuje od ostalih.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analiza teksta u R-u</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/alen-hu" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Predgovor</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./1_0_UVOD U ANALIZU TEKSTA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">UVOD U ANALIZU TEKSTA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_1_uvod_u_analizu_teksta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Uvod u analizu teksta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_2_primjena_analize_teksta_u_znanstvenim_istraživanjima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Primjena analize teksta u znanstvenim istraživanjima</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./2_0_POČETAK U RADU S TEKSTOM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">POČETAK U RADU S TEKSTOM</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_1_tekstualni_nizovi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Tekstualni nizovi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_2_regularni_izrazi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regularni izrazi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_3_učitavanje_i_oblikovanje_podataka.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Učitavanje i oblikovanje podataka</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_4_pretpostavke_za_analizu_teksta_u_tidytext-u.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pretpostavke za analizu teksta u tidytext-u</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">3_0_POČETAK U RADU S TEKSTOM.qmd</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_1_deskriptivna_analiza_teksta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Deskriptivna analiza teksta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_2_analiza_učestalosti_riječi.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza učestalosti riječi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_3_odnosi_među_riječima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Odnosi među riječima</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./4_0_ANALIZA_SENTIMENATA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANALIZA SENTIMENATA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_1_analiza_sentimenata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analiza sentimenta</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./5_0_TEKSTUALNA_MODELIRANJA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TEKSTUALNA MODELIRANJA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5_1_tematsko_modeliranje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Tematsko modeliranje</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./6_0_DODATNE_MOGUĆNOSTI_RADA_S_TEKSTOM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DODATNE MOGUĆNOSTI RADA S TEKSTOM</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6_1_rad_s_neurednim_podacima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Rad s neurednim podacima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6_2_vizualizacije_teksta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vizualizacija teksta</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatura</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="3">
    <h2 id="toc-title">Sadržaj poglavlja</h2>
   
  <ul>
  <li><a href="#zipfov-zakon" id="toc-zipfov-zakon" class="nav-link active" data-scroll-target="#zipfov-zakon"><span class="header-section-number">9.1</span> Zipfov zakon</a></li>
  <li><a href="#tf-idf-analiza" id="toc-tf-idf-analiza" class="nav-link" data-scroll-target="#tf-idf-analiza"><span class="header-section-number">9.2</span> tf-idf analiza</a></li>
  </ul>
<div class="quarto-other-links"><h2>Other Links</h2><ul><li><a href="ahusnjak0810@gmail.com"><i class="bi bi-chat-text"></i>Gmail</a></li><li><a href="www.linkedin.com/in/alen-husnjak-5a0bb9206"><i class="bi bi-linkedin"></i>LinkedIn</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>U prethodnom smo poglavlju učestalost riječi analizirali brojanjem, odnosno računanjem koliko se puta pojedina riječ pojavljuje u tekstu i koliki je njezin udio u ukupnom broju riječi. Takva analiza govori koje su riječi česte, ali ne i koje su važne. Veći broj pojavljivanja ne znači nužno da je riječ važnija za sadržaj teksta. U ovom ćemo poglavlju najprije pogledati kako je učestalost riječi u tekstu raspoređena, a zatim upoznati mjeru koja pokušava izdvojiti riječi koje su za pojedini tekst doista karakteristične.</p>
<section id="zipfov-zakon" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="zipfov-zakon"><span class="header-section-number">9.1</span> Zipfov zakon</h2>
<p>Raspodjela učestalosti riječi u jeziku slijedi pravilnost poznatu kao <strong>Zipfov zakon</strong>, nazvan prema američkom lingvistu Georgeu Zipfu. Prema tom zakonu, učestalost riječi obrnuto je proporcionalna njezinu rangu, odnosno mjestu na popisu riječi poredanih od najčešće prema najrjeđoj. Drugim riječima, druga najčešća riječ pojavljuje se otprilike upola rjeđe od najčešće, treća otprilike trećinu toliko često i tako dalje. Matematički se to može zapisati ovako:</p>
<p><span class="math inline">\(\text{Učestalost riječi} \propto \frac{1}{\text{rang riječi}}\)</span></p>
<p>Primjerice, ako se u nekom velikom tekstu najčešća riječ pojavljuje 10000 puta, druga najčešća pojavit će se otprilike 5000 puta, a treća otprilike 3333 puta. Posljedica je da malobrojne riječi, uglavnom zaustavne riječi poput <em>the</em>, <em>and</em> ili <em>of</em>, čine velik dio svakog teksta, dok se velika većina riječi pojavljuje tek nekoliko puta ili samo jednom.</p>
<p>Zipfov zakon možemo provjeriti na bajkama barda Beedlea s nekoliko funkcija iz paketa <code>dplyr</code>. Budući da nas zanima raspodjela učestalosti svih riječi u tekstu, koristimo tokenizirani tekst u izvornom obliku, sa zaustavnim riječima (<code>tToBtB_word_tokens</code>). Postupak je sljedeći:</p>
<ol type="1">
<li><p>Funkcijom <code>count()</code> brojimo koliko se puta svaka riječ pojavljuje u svakoj bajci. Argument <code>sort = TRUE</code> slaže riječi od najčešće prema najrjeđoj.</p></li>
<li><p>Podatke grupiramo prema bajci kako bi se sljedeći izračuni provodili zasebno za svaku bajku.</p></li>
<li><p>Funkcijom <code>mutate()</code> stvaramo tri nova stupca:</p></li>
</ol>
<ul>
<li><p><code>rank</code> - redni broj riječi na popisu poredanom prema učestalosti koji dobivamo funkcijom <code>row_number()</code>;</p></li>
<li><p><code>total</code> - ukupan broj riječi u bajci i</p></li>
<li><p><code>term_frequency</code> - relativnu učestalost riječi, odnosno njezin udio u ukupnom broju riječi u bajci.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rang i relativna učestalost riječi u svakoj bajci</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>tToBtB_freq_by_rank <span class="ot">&lt;-</span> tToBtB_word_tokens <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(fairy_tale, word, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fairy_tale) <span class="sc">|&gt;</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Rang riječi unutar bajke</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">rank =</span> <span class="fu">row_number</span>(),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Ukupan broj riječi u bajci</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">total =</span> <span class="fu">sum</span>(n),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Relativna učestalost riječi</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">term_frequency =</span> n <span class="sc">/</span> total</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Pregled</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>tToBtB_freq_by_rank</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,283 × 6
   fairy_tale                             word      n  rank total term_frequency
   &lt;chr&gt;                                  &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;          &lt;dbl&gt;
 1 4_babbitty_rabbitty_and_her_cackling_… the     159     1  1687         0.0943
 2 2_the_fountain_of_fair_fortune         the     146     1  1479         0.0987
 3 1_the_wizard_and_the_hopping_pot       the      86     1  1023         0.0841
 4 3_the_warlocks_hairy_heart             the      74     1  1096         0.0675
 5 2_the_fountain_of_fair_fortune         and      70     2  1479         0.0473
 6 4_babbitty_rabbitty_and_her_cackling_… and      69     2  1687         0.0409
 7 4_babbitty_rabbitty_and_her_cackling_… of       54     3  1687         0.0320
 8 1_the_wizard_and_the_hopping_pot       and      53     2  1023         0.0518
 9 3_the_warlocks_hairy_heart             and      47     2  1096         0.0429
10 5_the_tale_of_the_three_brothers       the      47     1   665         0.0707
# ℹ 2,273 more rows</code></pre>
</div>
</div>
<p>Stupac <code>rank</code> pokazuje mjesto svake riječi na popisu riječi u njezinoj bajci, poredanom od najčešće prema najrjeđoj.</p>
<p>Zipfov zakon najlakše je provjeriti na jednoj bajci, primjerice na bajci <em>The Fountain of Fair Fortune</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rang i relativna učestalost riječi u bajci The Fountain of Fair Fortune</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>tToBtB_freq_by_rank <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fairy_tale <span class="sc">==</span> <span class="st">"2_the_fountain_of_fair_fortune"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 554 × 6
   fairy_tale                     word      n  rank total term_frequency
   &lt;chr&gt;                          &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;          &lt;dbl&gt;
 1 2_the_fountain_of_fair_fortune the     146     1  1479         0.0987
 2 2_the_fountain_of_fair_fortune and      70     2  1479         0.0473
 3 2_the_fountain_of_fair_fortune of       45     3  1479         0.0304
 4 2_the_fountain_of_fair_fortune to       32     4  1479         0.0216
 5 2_the_fountain_of_fair_fortune her      25     5  1479         0.0169
 6 2_the_fountain_of_fair_fortune in       21     6  1479         0.0142
 7 2_the_fountain_of_fair_fortune was      21     7  1479         0.0142
 8 2_the_fountain_of_fair_fortune they     20     8  1479         0.0135
 9 2_the_fountain_of_fair_fortune a        18     9  1479         0.0122
10 2_the_fountain_of_fair_fortune she      18    10  1479         0.0122
# ℹ 544 more rows</code></pre>
</div>
</div>
<p>Bajka <em>The Fountain of Fair Fortune</em> ima ukupno 1479 riječi, od čega 554 različite. Najčešća riječ je <em>the</em> koja se pojavljuje 146 puta i čini 9,87 % svih riječi u bajci, pa je otprilike svaka deseta riječ <em>the</em>. Druga najčešća riječ, <em>and</em>, pojavljuje se 70 puta, a treća, <em>of</em>, 45 puta. Prema Zipfovu zakonu, riječ na rangu <em>r</em> trebala bi se pojavljivati otprilike 146 / <em>r</em> puta:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rang</th>
<th>Riječ</th>
<th>Očekivano (146 / <em>r</em>)</th>
<th>Opaženo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><em>the</em></td>
<td>146</td>
<td>146</td>
</tr>
<tr class="even">
<td>2</td>
<td><em>and</em></td>
<td>73</td>
<td>70</td>
</tr>
<tr class="odd">
<td>3</td>
<td><em>of</em></td>
<td>49</td>
<td>45</td>
</tr>
<tr class="even">
<td>4</td>
<td><em>to</em></td>
<td>37</td>
<td>32</td>
</tr>
<tr class="odd">
<td>5</td>
<td><em>her</em></td>
<td>29</td>
<td>25</td>
</tr>
<tr class="even">
<td>10</td>
<td><em>she</em></td>
<td>15</td>
<td>18</td>
</tr>
</tbody>
</table>
<p>Opažene se vrijednosti dobro slažu s onima koje predviđa Zipfov zakon, iako ne savršeno. Riječi na rangovima od 2 do 5 nešto su rjeđe od predviđenog, a riječ na rangu 10 nešto češća. Ispis pokazuje i drugu posljedicu Zipfova zakona. Svih deset najčešćih riječi zaustavne su riječi, a zajedno se pojavljuju 416 puta, pa čine 28 % svih riječi u bajci. Više od četvrtine riječi u tekstu, dakle, otpada na riječi koje ne govore ništa o njegovu sadržaju. Riječi koje se pojavljuju jednako često, poput <em>in</em> i <em>was</em> (po 21 put), dobivaju različite rangove (6 i 7) jer funkcija <code>row_number()</code> svakoj riječi dodjeljuje drugi redni broj.</p>
<p>Zipfov zakon obično se prikazuje grafom na kojem je rang na osi x, a relativna učestalost na osi y. Pritom obje osi imaju logaritamsku skalu. Na takvom grafu obrnuto proporcionalan odnos izgleda kao pravac s negativnim nagibom.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tToBtB_freq_by_rank, <span class="fu">aes</span>(<span class="at">x =</span> rank, <span class="at">y =</span> term_frequency, <span class="at">colour =</span> fairy_tale)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.1</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Rang"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Relativna učestalost"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"Bajka"</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">colour =</span> <span class="fu">guide_legend</span>(<span class="at">ncol =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="3_2_analiza_učestalosti_riječi_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Crte svih pet bajki gotovo se preklapaju i spuštaju od gornjeg lijevog prema donjem desnom kutu. Najčešće riječi, na rangu 1, čine između 7 i 10 % svih riječi u bajci, dok se riječi na rangu od nekoliko stotina pojavljuju sa samo nekoliko desetinki postotka. Budući da obje osi imaju logaritamsku skalu, takav pad, koji je kroz veći dio raspona približno ravna crta, upravo je ono što predviđa Zipfov zakon. Odnos ranga i relativne učestalosti, dakle, gotovo je jednak u svim bajkama, bez obzira na to o čemu govore.</p>
<p>Ipak, crte nisu posve ravne. Na desnom kraju pretvaraju se u vodoravne stube jer se mnogo rijetkih riječi pojavljuje jednako često, samo jednom ili dvaput, pa sve imaju istu relativnu učestalost. Crte su i različite duljine. Crta bajke <em>The Tale of the Three Brothers</em> završava ranije i na višoj vrijednosti od ostalih jer je ta bajka najkraća pa ima manje različitih riječi, a riječ koja se u njoj pojavi samo jednom čini veći udio svih riječi. Zato ćemo nagib izračunati za srednji dio raspona ranga u kojem je odnos najpravilniji. Za to koristimo funkciju <code>lm()</code> koja procjenjuje linearni model. Budući da je odnos linearan tek na logaritamskoj skali, u model unosimo logaritme ranga i relativne učestalosti (<code>log10()</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Riječi srednjeg raspona ranga</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>tToBtB_rank_subset <span class="ot">&lt;-</span> tToBtB_freq_by_rank <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(rank <span class="sc">&gt;</span> <span class="dv">10</span>, rank <span class="sc">&lt;</span> <span class="dv">500</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Linearni model logaritma relativne učestalosti i logaritma ranga</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>tToBtB_zipf_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log10</span>(term_frequency) <span class="sc">~</span> <span class="fu">log10</span>(rank), <span class="at">data =</span> tToBtB_rank_subset)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>tToBtB_zipf_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log10(term_frequency) ~ log10(rank), data = tToBtB_rank_subset)

Coefficients:
(Intercept)  log10(rank)  
    -1.2107      -0.7566  </code></pre>
</div>
</div>
<p>Ispis prikazuje dva koeficijenta. Odsječak (<code>(Intercept)</code>) iznosi -1,21, a nagib (koeficijent uz <code>log10(rank)</code>) -0,76. Nagib je najvažniji jer pokazuje koliko brzo relativna učestalost pada s porastom ranga. U klasičnom obliku Zipfova zakona nagib je -1, a što znači da se dvostrukim povećanjem ranga učestalost smanjuje upola. Nagib od -0,76 znači da pri dvostrukom povećanju ranga relativna učestalost pada na otprilike 59 % prethodne vrijednosti (2<sup>−0,76</sup> ≈ 0,59), a ne na 50 %. U bajkama, dakle, učestalost riječi u srednjem dijelu raspona pada nešto sporije nego što predviđa klasični Zipfov zakon, ali je obrazac i dalje jasno potencijski.</p>
<p>Blaži nagib dijelom je posljedica kratkoće bajki. Svaka bajka ima tek nekoliko stotina različitih riječi, pa raspon ranga od 10 do 500 obuhvaća i velik broj riječi koje se pojavljuju samo jednom ili dvaput. Kao što smo vidjeli na grafu, takve riječi čine vodoravne stube pa u tom dijelu učestalost gotovo ne pada, a što ublažava procijenjeni nagib. U duljim tekstovima, poput romana, nagib je obično bliži -1.</p>
<p>Procijenjeni pravac možemo ucrtati u graf. Funkcija <code>coef()</code> izdvaja koeficijente modela, prvi je odsječak na osi y (<code>intercept</code>), a drugi nagib (<code>slope</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafički prikaz Zipfova zakona s procijenjenim pravcem</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tToBtB_freq_by_rank, <span class="fu">aes</span>(<span class="at">x =</span> rank, <span class="at">y =</span> term_frequency, <span class="at">colour =</span> fairy_tale)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">intercept =</span> <span class="fu">coef</span>(tToBtB_zipf_model)[<span class="dv">1</span>],</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">slope =</span> <span class="fu">coef</span>(tToBtB_zipf_model)[<span class="dv">2</span>],</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"gray50"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="dv">2</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.1</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Rang"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Relativna učestalost"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"Bajka"</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="3_2_analiza_učestalosti_riječi_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ovakva se analiza može proširiti i na usporedbu različitih autora ili bilo kojih drugih zbirki tekstova, a zahvaljujući urednom obliku podataka provodi se istim postupkom.</p>
</section>
<section id="tf-idf-analiza" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="tf-idf-analiza"><span class="header-section-number">9.2</span> tf-idf analiza</h2>
<p>Zipfov zakon pokazuje da su najčešće riječi u tekstu uglavnom one koje o njegovu sadržaju govore najmanje, no, slijedeći prikazani zakon, ostaje pronaći riječi koje su za neki tekst doista važne. Dva su takva pristupa u analizi učestalosti riječi.</p>
<p>Jedan je pristup <strong>učestalost pojma</strong> (engl. <em>term frequency</em>, <strong>tf</strong>), odnosno relativna učestalost riječi u dokumentu koju smo računali i u prethodnom poglavlju. Što se riječ češće pojavljuje u dokumentu, to je vjerojatnije da je za njega važna. No mnoge su riječi česte u svim dokumentima pa ne govore ništa o tome po čemu se pojedini dokument razlikuje od ostalih.</p>
<p>Drugi je pristup <strong>inverzna učestalost dokumenata</strong> (engl. <em>inverse document frequency</em>, <strong>idf</strong>). Ona pokazuje u koliko se dokumenata u zbirci riječ pojavljuje. Pritom riječ koja se pojavljuje u svim dokumentima dobiva idf 0, a što je u manje dokumenata, to joj je idf veći. Računa se kao prirodni logaritam omjera ukupnog broja dokumenata i broja dokumenata koji sadrže riječ:</p>
<p><span class="math inline">\(\text{idf} = \ln \left( \frac{\text{broj dokumenata}}{\text{broj dokumenata koji sadrže riječ}} \right)\)</span></p>
<p>U našem slučaju dokumenti su bajke pa riječ koja se pojavljuje u samo jednoj od pet bajki ima idf = ln(5/1) ≈ 1,61, riječ koja se pojavljuje u dvije bajke ln(5/2) ≈ 0,92, a riječ koja se pojavljuje u svih pet ln(5/5) = 0.</p>
<p>Umnožak te dvije mjere je <strong>tf-idf</strong>, odnosno mjera prema kojoj riječ ima visok tf-idf ako se (1) često pojavljuje u jednom dokumentu (visok tf), a (2) rijetka je u ostalim dokumentima (visok idf). Tako tf-idf izdvaja riječi koje su karakteristične za pojedini dokument unutar zbirke dokumenata.</p>
<p>Tf-idf se računa funkcijom <code>bind_tf_idf()</code> iz paketa <code>tidytext</code>. Funkcija kao ulaz očekuje tablicu u kojoj svaki redak sadrži jedan pojam iz jednog dokumenta i broj njegovih pojavljivanja u tom dokumentu. Zato najprije funkcijom <code>count()</code> prebrojimo lematizirane riječi u svakoj bajci. Funkciji <code>bind_tf_idf()</code> zatim zadajemo tri argumenta:</p>
<ul>
<li><p><code>term</code> - stupac s riječima,</p></li>
<li><p><code>document</code> - stupac s dokumentima (bajke) i</p></li>
<li><p><code>n</code> - stupac s brojem pojavljivanja.</p></li>
</ul>
<p>Funkcija tablici dodaje tri nova stupca, <code>tf</code>, <code>idf</code> i <code>tf_idf</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Izračun tf-a, idf-a i tf-idf-a</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>tToBtB_tf_idf <span class="ot">&lt;-</span> tToBtB_word_tokens_stop_words_lemmatize <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(fairy_tale, lemma, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_tf_idf</span>(</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">term =</span> lemma,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">document =</span> fairy_tale,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> n</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(tf_idf))</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Pregled</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>tToBtB_tf_idf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,421 × 6
   fairy_tale                                  lemma       n     tf   idf tf_idf
   &lt;chr&gt;                                       &lt;chr&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1 5_the_tale_of_the_three_brothers            brother    22 0.0982 1.61  0.158 
 2 1_the_wizard_and_the_hopping_pot            pot        23 0.0561 1.61  0.0903
 3 4_babbitty_rabbitty_and_her_cackling_stumps king       33 0.0482 1.61  0.0776
 4 4_babbitty_rabbitty_and_her_cackling_stumps charla…    27 0.0395 1.61  0.0635
 5 3_the_warlocks_hairy_heart                  warlock    13 0.0294 1.61  0.0473
 6 2_the_fountain_of_fair_fortune              founta…    16 0.0274 1.61  0.0441
 7 5_the_tale_of_the_three_brothers            death      18 0.0804 0.511 0.0410
 8 4_babbitty_rabbitty_and_her_cackling_stumps babbit…    17 0.0249 1.61  0.0400
 9 3_the_warlocks_hairy_heart                  warloc…    10 0.0226 1.61  0.0364
10 1_the_wizard_and_the_hopping_pot            clang       9 0.0220 1.61  0.0353
# ℹ 1,411 more rows</code></pre>
</div>
</div>
<p>Tablica prikazuje lematizirane riječi poredane od najveće prema najmanjoj vrijednosti tf-idf, a na vrhu su leme koje su najkarakterističnije za svoju bajku. Najveći tf-idf ima lema <em>brother</em> u bajci <em>The Tale of the Three Brothers</em> (0,158). Ona ima visoku relativnu učestalost u toj bajci (tf = 0,0982), odnosno čini gotovo 10 % njezinih riječi te se ne pojavljuje ni u jednoj drugoj bajci pa ima najveći mogući idf (idf = ln(5/1) ≈ 1,61).</p>
<p>Umnožak tih vrijednosti (0,0982 × 1,61 ≈ 0,158) čini je ključnom riječi koja opisuje tu bajku i razlikuje je od ostalih. Slično vrijedi i za ostale leme na vrhu tablice: <em>pot</em> i <em>clang</em> za bajku <em>The Wizard and the Hopping Pot</em>, <em>king</em>, <em>charlatan</em> i <em>babbitty</em> za bajku <em>Babbitty Rabbitty and Her Cackling Stumps</em>, <em>warlock</em> za bajku <em>The Warlock’s Hairy Heart</em> te <em>fountain</em> za bajku <em>The Fountain of Fair Fortune</em>. Gotovo sve imaju idf 1,61, a što znači da se svaka pojavljuje u samo jednoj bajci.</p>
<p>Kako idf mijenja poredak najbolje se vidi na lemi <em>death</em>. U bajci <em>The Tale of the Three Brothers</em> ima drugu najveću relativnu učestalost od svih lema u tablici (tf = 0,0804), veću od leme <em>pot</em> u bajci <em>The Wizard and the Hopping Pot</em> (0,0561). Ipak, u tablici je tek sedma. Razlog je u tome što se pojavljuje i u još dvije bajke pa njezin idf iznosi samo ln(5/3) ≈ 0,51, a tf-idf 0,0804 × 0,51 ≈ 0,041. Smrt je, dakle, središnja tema bajke o trojici braće, ali riječ <em>death</em> ipak ne razlikuje tu bajku od ostalih tako jasno kao riječ <em>brother</em>.</p>
<p>Na suprotnom kraju tablice nalaze se riječi koje se pojavljuju u svim bajkama. Njihov idf iznosi ln(5/5) = 0, pa je i tf-idf 0, bez obzira na to koliko su česte. Takve riječi, koliko god bile česte, ne pomažu razlikovati jednu bajku od drugih.</p>
<p>Iste podatke možemo prikazati i grafički, s deset lema s najvećim tf-idf vrijednostima u svakoj bajci.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Riječi s najvećim tf-idf vrijednostima po bajkama</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>tToBtB_tf_idf <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fairy_tale) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(tf_idf, <span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> tf_idf, <span class="at">y =</span> <span class="fu">reorder_within</span>(lemma, tf_idf, fairy_tale), <span class="at">fill =</span> fairy_tale)) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>fairy_tale, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_reordered</span>() <span class="sc">+</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"tf-idf"</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Lema"</span>,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Najkarakterističnije riječi po bajci"</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="3_2_analiza_učestalosti_riječi_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Graf pokazuje po čemu se bajke međusobno razlikuju. Najkarakterističnije riječi uglavnom su likovi, imena i predmeti oko kojih se vrti radnja pojedine bajke. U bajci <em>The Wizard and the Hopping Pot</em> to su lonac (<em>pot</em>) i zvukovi koje proizvodi (<em>clang</em>, <em>groan</em>), u bajci <em>The Fountain of Fair Fortune</em> fontana (<em>fountain</em>), vitez (<em>knight</em>) i imena triju vještica (<em>amata</em>, <em>asha</em>, <em>altheda</em>), u bajci <em>The Warlock’s Hairy Heart</em> čarobnjak (<em>warlock</em>), djevojka (<em>maiden</em>) i srce (<em>heart</em>), u bajci <em>Babbitty Rabbitty and Her Cackling Stumps</em> kralj (<em>king</em>), šarlatan (<em>charlatan</em>) i sama Babbitty, a u bajci <em>The Tale of the Three Brothers</em> braća (<em>brother</em>), smrt (<em>death</em>), rijeka (<em>river</em>) i plašt (<em>cloak</em>). Zanimljivo je da se u svakoj bajci među najkarakterističnijim riječima nalazi i riječ iz njezina naslova.</p>
<p>Graf pokazuje i koliko se bajke razlikuju po tome koliko se jedna riječ ističe. U bajci <em>The Tale of the Three Brothers</em> riječ <em>brother</em> ima gotovo četiri puta veći tf-idf od sljedeće riječi, <em>death</em>, pa tu bajku određuje jedna riječ. U ostalim se bajkama vrijednosti smanjuju postupnije pa ih opisuje skupina riječi. To je i svrha mjere tf-idf, izdvojiti riječi koje su važne za jedan dokument unutar zbirke dokumenata, a koje ga ujedno razlikuju od ostalih dokumenata.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./3_1_deskriptivna_analiza_teksta.html" class="pagination-link" aria-label="Deskriptivna analiza teksta">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Deskriptivna analiza teksta</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./3_3_odnosi_među_riječima.html" class="pagination-link" aria-label="Odnosi među riječima">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Odnosi među riječima</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, Alen Husnjak</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="./www.linkedin.com/in/alen-husnjak-5a0bb9206">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>